### ISSUE TITLE
Current ideas that I post on forum ( just to remind, and maybe I will have more ideas)

### ISSUE THREAD

**Issue by Majber** [satyrlord/stellarisplus#2]
- [x] 1. Is UI Overhaul 1080p do same work as Bigger Empire View , I think yes? So maybe its not necessary to merge both? (keep UI Overhaul 1080p, its constantly updating)
- [x] 2. Fixed Prethoryn Scourge Bombardment is already included in 1.03 patch
- [x] 3. "More Aggressive AI" mod and "AI Rebalance" change same thing, maybe just pick agression code and don't include "More Aggressive AI"? (AI Rebalance will develop more in the future I think and "More Aggressive AI" will stay the same. Also in next big patch we will have option to pick how aggressive AI we want)
- [x] ~~4. "Beautiful Battles" and "Strike Craft Range Rebalance" will overlap Strike Craft Range Rebalance feature, just pick specific code (if its not already in "Beautiful Battles") from "Strike Craft Range Rebalance" or don't include this mod (Beautiful Battles is more complex and will develop more in future)~~

**Comment by satyrlord** [comment]
Thanks, will do.

**Comment by Majber** [comment]
5. 2D galaxy mod isnt dont work with Beautiful Battles mod, comment from 2D galaxy mod comment section: "The problems with Beautiful Battles would be because the ships in BB are coded to move around on the Z-plane, and this mod - according to the description - removes the Z-plane"  . I personally will wait with Beautiful Battles integration becouse next big patch (beta in late next week) can change a lot things.

**Comment by satyrlord** [comment]
I have completely removed Beautiful Battles for now as it fills up my error.log with a lot of errors which I don't know how to solve.

**Comment by satyrlord** [comment]
Fixed issues, please test.
